"""create initial schema

Revision ID: e19bd6762efe
Revises: 
Create Date: 2026-09-18 03:49:21.457497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e19bd6762efe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judge_personas',
    sa.Column('persona_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_personas_persona_type'), 'judge_personas', ['persona_type'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('pitches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('startup_name', sa.String(length=255), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('target_users', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('why_ai', sa.Text(), nullable=True),
    sa.Column('traction', sa.Text(), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('ask', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitches_user_id'), 'pitches', ['user_id'], unique=False)
    op.create_table('simulation_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=True),
    sa.Column('judge_persona_id', sa.UUID(), nullable=False),
    sa.Column('pitch_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('judge_config_version', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.Enum('PRACTICE', 'JUDGE', 'INVESTOR', name='difficulty'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', 'FAILED', name='simulation_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('current_phase', sa.Enum('PITCH_BATTLE', 'PITCH_SCORING', 'RETRY', 'DEAL', 'DEAL_SCORING', 'COMPLETED', name='simulation_phase'), server_default=sa.text("'PITCH_BATTLE'"), nullable=False),
    sa.Column('battle_round_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deal_round_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deal_status', sa.Enum('NOT_AVAILABLE', 'AVAILABLE', 'SKIPPED', 'COMPLETED', name='deal_status'), server_default=sa.text("'NOT_AVAILABLE'"), nullable=False),
    sa.Column('deal_type', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('battle_round_count >= 0', name='ck_simulation_sessions_battle_round_count_nonneg'),
    sa.CheckConstraint('deal_round_count >= 0', name='ck_simulation_sessions_deal_round_count_nonneg'),
    sa.ForeignKeyConstraint(['judge_persona_id'], ['judge_personas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_sessions_judge_persona_id'), 'simulation_sessions', ['judge_persona_id'], unique=False)
    op.create_index(op.f('ix_simulation_sessions_pitch_id'), 'simulation_sessions', ['pitch_id'], unique=False)
    op.create_index(op.f('ix_simulation_sessions_user_id'), 'simulation_sessions', ['user_id'], unique=False)
    op.create_index('ix_simulation_sessions_user_id_created_at', 'simulation_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_simulation_sessions_user_id_status', 'simulation_sessions', ['user_id', 'status'], unique=False)
    op.create_table('scorecards',
    sa.Column('simulation_session_id', sa.UUID(), nullable=False),
    sa.Column('scorecard_type', sa.Enum('PITCH', 'DEAL', 'FINAL', name='scorecard_type'), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_label', sa.String(length=64), nullable=True),
    sa.Column('rubric_version', sa.String(length=64), nullable=False),
    sa.Column('basis', sa.String(length=32), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('coaching', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name='ck_scorecards_overall_score_range'),
    sa.ForeignKeyConstraint(['simulation_session_id'], ['simulation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_session_id', 'scorecard_type', name='uq_scorecards_session_type')
    )
    op.create_index(op.f('ix_scorecards_simulation_session_id'), 'scorecards', ['simulation_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scorecards_simulation_session_id'), table_name='scorecards')
    op.drop_table('scorecards')
    op.drop_index('ix_simulation_sessions_user_id_status', table_name='simulation_sessions')
    op.drop_index('ix_simulation_sessions_user_id_created_at', table_name='simulation_sessions')
    op.drop_index(op.f('ix_simulation_sessions_user_id'), table_name='simulation_sessions')
    op.drop_index(op.f('ix_simulation_sessions_pitch_id'), table_name='simulation_sessions')
    op.drop_index(op.f('ix_simulation_sessions_judge_persona_id'), table_name='simulation_sessions')
    op.drop_table('simulation_sessions')
    op.drop_index(op.f('ix_pitches_user_id'), table_name='pitches')
    op.drop_table('pitches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_judge_personas_persona_type'), table_name='judge_personas')
    op.drop_table('judge_personas')
    # ### end Alembic commands ###

    # Manually added: op.drop_table() does not drop the native PostgreSQL
    # ENUM types it implicitly created — without this, downgrade() leaves
    # orphaned types behind and a subsequent upgrade() fails with
    # "type already exists".
    bind = op.get_bind()
    postgresql.ENUM(name='scorecard_type').drop(bind, checkfirst=True)
    postgresql.ENUM(name='deal_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='simulation_phase').drop(bind, checkfirst=True)
    postgresql.ENUM(name='simulation_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='difficulty').drop(bind, checkfirst=True)
